### ISSUE TITLE
Clicking 'add another' adds two more clusters on 'Editors' section (production)

### ISSUE THREAD

**Issue by j-basford** [scientist-softserv/britishlibrary#414]

**Comment by cziaarm** [comment]
Fixed?

**Comment by grahamjevon** [comment]
I thought this was still an issue. But just tested on production and works as expected. I guess it is fixed.
